### ISSUE TITLE
Crash from removing AE drive not EE drive from drive bay

### ISSUE THREAD

**Issue by Pultex** [Mordenkainen/EquivalentEnergistics#124]
While using ProjectE 1.3.0, and newest AE. [part of Foolcraft3]
When using the new version of AE the mod crashes with this error if you remove the AE drive.

`java.lang.AbstractMethodError: com.mordenkainen.equivalentenergistics.items.ItemEMCCell.getCellInventory(Lnet/minecraft/item/ItemStack;Lappeng/api/storage/ISaveProvider;Lappeng/api/storage/IStorageChannel;)Lappeng/api/storage/ICellInventoryHandler;
	at appeng.tile.storage.TileDrive.updateState(TileDrive.java:302)
	at appeng.tile.storage.TileDrive.onReady(TileDrive.java:331)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:220)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1818_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
`
So which version of AE was this made for would be nice to know.

Placing the EE blocks seems to connect to the system just once the storage drive is inserted the system loses everything in it then when taking out the AE storage drive it can only see the EE drive and crashes.

Crash immediately will occur on world load.

**Comment by Mordenkainen** [comment]
This is made for AE2 RV5. RV6 is an alpha and not supported by most addons at this point.

It looks like you may be running RV6.

**Comment by Pultex** [comment]
thank you
