### ISSUE TITLE
Crash on servers

### ISSUE THREAD

**Issue by HyCraftHD** [Mordenkainen/EquivalentEnergistics#147]
This method will crash the server as it uses a client only class (I18n)

https://github.com/Mordenkainen/EquivalentEnergistics/blob/0559fee3dd72bc8932957f70414c0a4b32f371b9/src/main/java/com/mordenkainen/equivalentenergistics/integration/ae2/cache/crafting/EMCCraftingGrid.java#L154

``` java
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_232]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_232]
	at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.createPattern(EMCCraftingGrid.java:154) ~[EMCCraftingGrid.class:?]
	at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.addPattern(EMCCraftingGrid.java:85) ~[EMCCraftingGrid.class:?]
	at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.updatePatterns(EMCCraftingGrid.java:77) ~[EMCCraftingGrid.class:?]
	at com.mordenkainen.equivalentenergistics.integration.ae2.grid.GridUtils.updatePatterns(GridUtils.java:200) ~[GridUtils.class:?]
	at com.mordenkainen.equivalentenergistics.blocks.crafter.tiles.TileEMCCrafter.setCurrentTome(TileEMCCrafter.java:159) ~[TileEMCCrafter.class:?]
	at com.mordenkainen.equivalentenergistics.blocks.crafter.BlockEMCCrafter.onBlockActivated(BlockEMCCrafter.java:88) ~[BlockEMCCrafter.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:449) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_232]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
```

**Comment by Mordenkainen** [comment]
Thanks. Did not realize that was a client only class

**Comment by Jinaie** [comment]
still nothing to resolve this ive got the same error =p

**Comment by ewanm89** [comment]
@Jinaie that would be why the bug report is still open, it is pending to be in the next release.

**Comment by Jinaie** [comment]
> @Jinaie that would be why the bug report is still open, it is pending to be in the next release.

AH ! I didnt know XD I quite new to this and quite easely panicking to error i get XD. So do we have a date for the new release ? =p
