### ISSUE TITLE
EE3 error with ProjectE installed results with crash

### ISSUE THREAD

**Issue by kokono2** [Mordenkainen/EquivalentEnergistics#34]
I'm getting the following error with the 0.4 version of Equivalent Energistics. I have ProjectE installed, but the error says something about EE3.

# log:
	cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/pahimar/ee3/api/event/PlayerKnowledgeEvent
		at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
		at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
		at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
		at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
		at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
		at net.minecraft.client.main.Main.main(SourceFile:148)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
		at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
		at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
		at org.multimc.EntryPoint.listen(EntryPoint.java:170)
		at org.multimc.EntryPoint.main(EntryPoint.java:54)
	Caused by: java.lang.NoClassDefFoundError: com/pahimar/ee3/api/event/PlayerKnowledgeEvent
		at java.lang.Class.getDeclaredMethods0(Native Method)
		at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
		at java.lang.Class.privateGetPublicMethods(Unknown Source)
		at java.lang.Class.getMethods(Unknown Source)
		at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:60)
		at com.mordenkainen.equivalentenergistics.util.EventHandlerModule.<init>(EventHandlerModule.java:21)
		at com.mordenkainen.equivalentenergistics.EquivalentEnergistics.init(EquivalentEnergistics.java:92)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
		at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
		at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
		at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
		at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
		at com.google.common.eventbus.EventBus.post(EventBus.java:275)
		at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
		at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
		at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
		at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
		at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
		at com.google.common.eventbus.EventBus.post(EventBus.java:275)
		at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
		at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
		... 18 more
	Caused by: java.lang.ClassNotFoundException: com.pahimar.ee3.api.event.PlayerKnowledgeEvent
		at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		... 51 more
	Caused by: java.lang.NullPointerException

**Comment by Mordenkainen** [comment]
Can you post your config file?

**Comment by Mordenkainen** [comment]
Nevermind, just try 0.5
