### ISSUE TITLE
Internal Server Error when insert Alchenomicon EE3

### ISSUE THREAD

**Issue by Appa1990** [Mordenkainen/EquivalentEnergistics#73]
Hello,
we have an issue when we put our Alconomicons in the EMC Assembler. The server kicks us with internal server error message. After reconnect we dont have the recipes in the AE system and the Alconomicon duplicates.

weve also installed PlayerAPI-1.7.10-1.4

EquivalentExchange3-1.7.10-0.3.0.547
We play an customized FTB Infinity 3.0.1

whole server crashes now...

greets Appa1990

**Comment by Mordenkainen** [comment]
Do you have a crashlog?

There should be some kind of error logged on the server and/or client. Without some clue as to the failing code, I wouldn't know where to start looking.

Does the server only kick the player who placed the Alchenomicon, all players, nearby players, etc?
When you say the whole server crashes now, is this when the tome is placed, on startup, when a player goes to the chunk the assembler is in, etc?

**Comment by Appa1990** [comment]
The Server only kicks the player who put in the alchonomicon. after rejoin this player have one alchonomicon in hand and another one in the Assembler. After that we try a restart. then the server crashes and never came back! Until we uninstalled ur mod ;(


Thats one of the logs i found!
[23:34:24] [Server thread/INFO]: Starting minecraft server version 1.7.10
[23:35:56] [Server thread/INFO]: Loading properties
[23:35:56] [Server thread/INFO]: Default game type: SURVIVAL
[23:35:56] [Server thread/INFO]: Generating keypair
[23:35:57] [Server thread/INFO]: Starting Minecraft server on 31.214.166.5:25565
[23:37:07] [Server thread/INFO]: Preparing level "world"
[23:37:58] [Server thread/INFO]: Preparing start region for level 0
[23:37:59] [Server thread/INFO]: Done (53.231s)! For help, type "help" or "?"
[23:37:59] [Server thread/INFO]: Starting GS4 status listener
[23:37:59] [Query Listener #1/INFO]: Query running on 31.214.166.5:25565
[23:38:07] [Server thread/INFO]: Saving...
[23:38:08] [Server thread/INFO]: Saved the world
[23:38:12] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418) ~[?:1.8.0_101]
	at java.util.ArrayList.get(ArrayList.java:431) ~[?:1.8.0_101]
	at com.mordenkainen.equivalentenergistics.integration.ae2.EMCCraftingPattern.createItemPattern(EMCCraftingPattern.java:126) ~[EMCCraftingPattern.class:?]
	at com.mordenkainen.equivalentenergistics.integration.ae2.EMCCraftingPattern.buildPattern(EMCCraftingPattern.java:87) ~[EMCCraftingPattern.class:?]
	at com.mordenkainen.equivalentenergistics.integration.ae2.EMCCraftingPattern.<init>(EMCCraftingPattern.java:27) ~[EMCCraftingPattern.class:?]
	at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.createPattern(EMCCraftingGrid.java:149) ~[EMCCraftingGrid.class:?]
	at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.addPattern(EMCCraftingGrid.java:84) ~[EMCCraftingGrid.class:?]
	at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.updatePatterns(EMCCraftingGrid.java:76) ~[EMCCraftingGrid.class:?]
	at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.onUpdateTick(EMCCraftingGrid.java:45) ~[EMCCraftingGrid.class:?]
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43) ~[GridCacheWrapper.class:?]
	at appeng.me.Grid.update(Grid.java:280) ~[Grid.class:?]
	at appeng.hooks.TickHandler.onTick(TickHandler.java:239) ~[TickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_692_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:38:12] [Server thread/ERROR]: This crash report has been saved to: /games/ni41764_1/ftproot/minecraftftb/./crash-reports/crash-2017-08-11_23.38.12-server.txt
[23:38:12] [Server thread/INFO]: Stopping server
[23:38:12] [Server thread/INFO]: Saving players
[23:38:12] [Server thread/INFO]: Saving worlds
[23:38:12] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[23:38:12] [Server thread/INFO]: Saving chunks for level 'world'/Nether
[23:38:12] [Server thread/INFO]: Saving chunks for level 'world'/The End
[23:38:12] [Server thread/INFO]: Saving chunks for level 'world'/Asteroids
[23:38:12] [Server thread/INFO]: Saving chunks for level 'world'/Twilight Forest
[23:38:12] [Server thread/INFO]: Saving chunks for level 'world'/Underdark
[23:38:12] [Server thread/INFO]: Saving chunks for level 'world'/Dungeon
[23:38:12] [Server thread/INFO]: Saving chunks for level 'world'/Spirit World
[23:38:12] [Server thread/INFO]: Saving chunks for level 'world'/Torment
[23:38:12] [Server thread/INFO]: Saving chunks for level 'world'/Mirror
[23:38:12] [Server thread/INFO]: Saving chunks for level 'world'/The Outer Lands
[23:38:12] [Server thread/INFO]: Saving chunks for level 'world'/Bedrock
[23:38:12] [Server thread/INFO]: Saving chunks for level 'world'/The Last Millenium
[23:38:12] [Server thread/INFO]: Saving chunks for level 'world'/Moon
[23:38:12] [Server thread/INFO]: Saving chunks for level 'world'/Mars
[23:38:12] [Server thread/INFO]: Saving chunks for level 'world'/Mining World

heres another

[23:30:10] [Server thread/INFO]: Starting minecraft server version 1.7.10
[23:31:40] [Server thread/INFO]: Loading properties
[23:31:40] [Server thread/INFO]: Default game type: SURVIVAL
[23:31:40] [Server thread/INFO]: Generating keypair
[23:31:40] [Server thread/INFO]: Starting Minecraft server on 31.214.166.5:25565
[23:32:47] [Server thread/INFO]: Preparing level "world"
[23:33:47] [Server thread/INFO]: Preparing start region for level 0
[23:33:48] [Server thread/INFO]: Done (61.627s)! For help, type "help" or "?"
[23:33:48] [Server thread/INFO]: Starting GS4 status listener
[23:33:48] [Query Listener #1/INFO]: Query running on 31.214.166.5:25565
[23:33:58] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418) ~[?:1.8.0_101]
	at java.util.ArrayList.get(ArrayList.java:431) ~[?:1.8.0_101]
	at com.mordenkainen.equivalentenergistics.integration.ae2.EMCCraftingPattern.createItemPattern(EMCCraftingPattern.java:126) ~[EMCCraftingPattern.class:?]
	at com.mordenkainen.equivalentenergistics.integration.ae2.EMCCraftingPattern.buildPattern(EMCCraftingPattern.java:87) ~[EMCCraftingPattern.class:?]
	at com.mordenkainen.equivalentenergistics.integration.ae2.EMCCraftingPattern.<init>(EMCCraftingPattern.java:27) ~[EMCCraftingPattern.class:?]
	at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.createPattern(EMCCraftingGrid.java:149) ~[EMCCraftingGrid.class:?]
	at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.addPattern(EMCCraftingGrid.java:84) ~[EMCCraftingGrid.class:?]
	at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.updatePatterns(EMCCraftingGrid.java:76) ~[EMCCraftingGrid.class:?]
	at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.onUpdateTick(EMCCraftingGrid.java:45) ~[EMCCraftingGrid.class:?]
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43) ~[GridCacheWrapper.class:?]
	at appeng.me.Grid.update(Grid.java:280) ~[Grid.class:?]
	at appeng.hooks.TickHandler.onTick(TickHandler.java:239) ~[TickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_692_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:33:58] [Server thread/ERROR]: This crash report has been saved to: /games/ni41764_1/ftproot/minecraftftb/./crash-reports/crash-2017-08-11_23.33.58-server.txt
[23:33:58] [Server thread/INFO]: Stopping server
[23:33:58] [Server thread/INFO]: Saving players
[23:33:58] [Server thread/INFO]: Saving worlds
[23:33:58] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[23:33:58] [Server thread/INFO]: Saving chunks for level 'world'/Nether
[23:33:58] [Server thread/INFO]: Saving chunks for level 'world'/The End
[23:33:58] [Server thread/INFO]: Saving chunks for level 'world'/Asteroids
[23:33:58] [Server thread/INFO]: Saving chunks for level 'world'/Twilight Forest
[23:33:58] [Server thread/INFO]: Saving chunks for level 'world'/Underdark
[23:33:58] [Server thread/INFO]: Saving chunks for level 'world'/Dungeon
[23:33:58] [Server thread/INFO]: Saving chunks for level 'world'/Spirit World
[23:33:58] [Server thread/INFO]: Saving chunks for level 'world'/Torment
[23:33:58] [Server thread/INFO]: Saving chunks for level 'world'/Mirror
[23:33:58] [Server thread/INFO]: Saving chunks for level 'world'/The Outer Lands
[23:33:58] [Server thread/INFO]: Saving chunks for level 'world'/Bedrock
[23:33:58] [Server thread/INFO]: Saving chunks for level 'world'/The Last Millenium
[23:33:58] [Server thread/INFO]: Saving chunks for level 'world'/Moon
[23:33:58] [Server thread/INFO]: Saving chunks for level 'world'/Mars
[23:33:58] [Server thread/INFO]: Saving chunks for level 'world'/Mining World

**Comment by Mordenkainen** [comment]
Excellent! Thanks for the info! Let me take a look and see if I can figure out what is going on here.

**Comment by Mordenkainen** [comment]
OK, I think I found the source of the issue. Any chance you could join my Discord?

https://discord.gg/NQQxNb3

**Comment by Appa1990** [comment]
I join the discord after finished working today! Think at 5pm gmt +1

**Comment by SADXfan01** [comment]
Any updates?

**Comment by Mordenkainen** [comment]
Kinda fell off my radar. Should have a new ver out within a couple of days.

**Comment by Appa1990** [comment]
That would be nice! Still need that

**Comment by Appa1990** [comment]
[energy-values.zip](https://github.com/Mordenkainen/EquivalentEnergistics/files/1586033/energy-values.zip)
Made a EE3 Fix for the issue. Works very well with FTB Infinity. Planks and all other items which had an EMC below 1 replaced now with 1. Just replace the Energy-values.json file with the old one in Minecraft/data/ee3/energy-values folder.
Also set Custom EMC to true in EE3 Settings

**Comment by Mordenkainen** [comment]
Fixed in 0.8
